- name: Run show version on Cisco router
  hosts: cisco_routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run show version
      ansible.netcommon.cli_command:
        command: show version

