all:
  children:
    cisco_routers:
      hosts:
        cisco-router-01:
          ansible_host: 10.32.20.210                         # Replace with your router IP
          ansible_user: ansible                              # Replace with your SSH username
          ansible_ssh_private_key_file: ~/.ssh/id_rsa        # Or your custom private key path
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: cisco.ios.ios
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
