---
- name: Backup Cisco Router Configuration
  hosts: cisco-router-01
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - name: Backup running configuration
      ios_config:
        backup: yes
      register: config_backup

    - name: Ensure backups directory exists on control node
      file:
        path: "playbooks/backups"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Fetch backup config from router to control node
      fetch:
        src: "{{ config_backup.backup_path }}"
        dest: "playbooks/backups/"
        flat: yes

    - name: Remove old backup file if exists
      file:
        path: "playbooks/backups/{{ inventory_hostname }}_backup.cfg"
        state: absent
      delegate_to: localhost

    - name: Rename fetched backup file with hostname
      shell: mv playbooks/backups/{{ config_backup.backup_path | basename }} playbooks/backups/{{ inventory_hostname }}_backup.cfg
      args:
        creates: "playbooks/backups/{{ inventory_hostname }}_backup.cfg"
      delegate_to: localhost

