---
- name: Restore Cisco Router Configuration (apply live)
  hosts: cisco-router-01
  gather_facts: no
  collections:
    - cisco.ios
    - ansible.netcommon

  vars:
    restore_file: "/home/ansible/cisco_router/backups/{{ inventory_hostname }}_backup.cfg"

  tasks:
    - name: Apply backup config live using ios_config
      ios_config:
        src: "{{ restore_file }}"

